//The ABI generated by Hardhat
import VaultArtifact from "../../web3/artifacts/contracts/TokenVault.sol/TokenVault.json";

export const VAULT_ABI = VaultArtifact.abi as const;

//Contract Deployment Address
export const VAULT_ADDRESS = "0x1234567890AbcdEf1234567890aBcdef12345678" as `0x${string}`;
